---
- name: Adding new user and setup git, sudo, mc, htop
  hosts: nginxserver
  become: yes
  tasks:
    - name: Install git, sudo, mc, htop
      apt:
        name: git, sudo, mc, htop
        state: latest


  pre_tasks:
        - name: Ensure group "docker" exists with correct gid
          ansible.builtin.group:
            name: docker
            state: present
            gid: 1750

        - name: Add user and ad user to groups
          user:
            name: testuser
            groups: sudo,docker
            create_home: yes
            append: yes
            password: "{{ '123456789' | password_hash('sha512') }}"