---
- name: install and start webserver
  hosts: web_servers
  become: true
  vars:
    http_port: 80
    server_name: "vhost_nginx"
  
  tasks:
    - name: nginx install
      apt:
        name: nginx
        state: latest
    
    - name: delete file default
      ansible.builtin.file:
        path:  /etc/nginx/sites-enabled/default
        state: absent

    - name: delete file default
      ansible.builtin.file:
        path:  /etc/nginx/sites-available/default
        state: absent

    - name: Setup nginx vhost
      template:
        src=./template/yoursite.com.conf.tpl
        dest=/etc/nginx/conf.d/tms.local.conf
  
    - name: create folder
      ansible.builtin.file:
        path: /var/www/html/{{ inventory_hostname }}
        state: directory


    - name: Get uptime and avg
      ansible.builtin.command: uptime
      register: upa

    - name: latest index.html file is present
      template:
        src: ./template/index.html.tpl
        dest: /var/www/html/{{ inventory_hostname }}/index.html
  
    - name: Setup nginx conf
      template:
        src=./template/nginx.conf.tpl
        dest=/etc/nginx/nginx.conf
      notify: restart nginx
  
  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted